name: audio_manager
description: A flutter plugin for music playback, including notification handling.
version: 1.0.0
homepage: https://github.com/jeromexiong/audio_manager
repository: https://github.com/jeromexiong/audio_manager
issue_tracker: https://github.com/jeromexiong/audio_manager/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

flutter:
  plugin:
    platforms:
      android:
        package: cc.dync.audio_manager
        pluginClass: AudioManagerPlugin
      ios:
        pluginClass: SwiftAudioManagerPlugin
      macos:
        pluginClass: AudioManagerPlugin
      windows:
        pluginClass: AudioManagerPlugin
      linux:
        pluginClass: AudioManagerPlugin
      web:
        pluginClass: AudioManagerPlugin
        fileName: audio_manager_web.dart
